/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as EmotionRouteImport } from './routes/emotion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DanceRouteImport } from './routes/dance'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as APIChatRouteImport } from './routes/API/chat'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionRoute = EmotionRouteImport.update({
  id: '/emotion',
  path: '/emotion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DanceRoute = DanceRouteImport.update({
  id: '/dance',
  path: '/dance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const APIChatRoute = APIChatRouteImport.update({
  id: '/API/chat',
  path: '/API/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dance': typeof DanceRoute
  '/dashboard': typeof DashboardRoute
  '/emotion': typeof EmotionRoute
  '/exercise': typeof ExerciseRoute
  '/games': typeof GamesRoute
  '/playlist': typeof PlaylistRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/API/chat': typeof APIChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dance': typeof DanceRoute
  '/dashboard': typeof DashboardRoute
  '/emotion': typeof EmotionRoute
  '/exercise': typeof ExerciseRoute
  '/games': typeof GamesRoute
  '/playlist': typeof PlaylistRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/API/chat': typeof APIChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dance': typeof DanceRoute
  '/dashboard': typeof DashboardRoute
  '/emotion': typeof EmotionRoute
  '/exercise': typeof ExerciseRoute
  '/games': typeof GamesRoute
  '/playlist': typeof PlaylistRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/API/chat': typeof APIChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dance'
    | '/dashboard'
    | '/emotion'
    | '/exercise'
    | '/games'
    | '/playlist'
    | '/profile'
    | '/reset-password'
    | '/API/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/dance'
    | '/dashboard'
    | '/emotion'
    | '/exercise'
    | '/games'
    | '/playlist'
    | '/profile'
    | '/reset-password'
    | '/API/chat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/dance'
    | '/dashboard'
    | '/emotion'
    | '/exercise'
    | '/games'
    | '/playlist'
    | '/profile'
    | '/reset-password'
    | '/API/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DanceRoute: typeof DanceRoute
  DashboardRoute: typeof DashboardRoute
  EmotionRoute: typeof EmotionRoute
  ExerciseRoute: typeof ExerciseRoute
  GamesRoute: typeof GamesRoute
  PlaylistRoute: typeof PlaylistRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  APIChatRoute: typeof APIChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotion': {
      id: '/emotion'
      path: '/emotion'
      fullPath: '/emotion'
      preLoaderRoute: typeof EmotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dance': {
      id: '/dance'
      path: '/dance'
      fullPath: '/dance'
      preLoaderRoute: typeof DanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/API/chat': {
      id: '/API/chat'
      path: '/API/chat'
      fullPath: '/API/chat'
      preLoaderRoute: typeof APIChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DanceRoute: DanceRoute,
  DashboardRoute: DashboardRoute,
  EmotionRoute: EmotionRoute,
  ExerciseRoute: ExerciseRoute,
  GamesRoute: GamesRoute,
  PlaylistRoute: PlaylistRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  APIChatRoute: APIChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
